- name: Check if K3s is already installed
  stat:
    path: /etc/rancher/k3s/k3s.yaml
  register: k3s_installed

- name: Install K3s on master1
  shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION="v1.30.1+k3s1" INSTALL_K3S_EXEC="server --cluster-init --node-taint CriticalAddonsOnly=true:NoExecute --tls-san {{ ansible_host }}" sh -
  args:
    executable: /bin/bash
  when: not k3s_installed.stat.exists

- name: Wait for node-token to appear
  wait_for:
    path: /var/lib/rancher/k3s/server/node-token
    timeout: 60
  when: not k3s_installed.stat.exists

- name: Read node token
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: node_token

- name: Set fact for token
  set_fact:
    k3s_token: "{{ node_token['content'] | b64decode | trim }}"

- name: Save token for other hosts
  copy:
    content: "{{ k3s_token }}"
    dest: /tmp/k3s_token_shared
